import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { BookProvider } from "../context/BookContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Book Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BookProvider>{children}</BookProvider>
      </body>
    </html>
  );
}
